# Generated by Django 5.1.4 on 2025-01-06 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_item',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
