# Generated by Django 5.1.4 on 2025-01-09 20:25

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_invoice_item_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Uid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_#$&@', length=12, max_length=17, prefix='', unique=True),
        ),
    ]
