# Generated by Django 5.1.4 on 2025-01-09 21:19

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_invoice_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='Uid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz', length=12, max_length=17, prefix='Inv-', unique=True),
        ),
    ]
