# Generated by Django 5.1.4 on 2025-01-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
