# Generated by Django 5.1.4 on 2025-01-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('NGN', 'NGN'), ('YEN', 'YEN')], default='USD', max_length=100),
        ),
    ]
