# Generated by Django 5.1.4 on 2025-01-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
