# Generated by Django 5.1.4 on 2025-01-25 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.invoice'),
        ),
    ]
