# Generated by Django 5.1.4 on 2025-01-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_receipt_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
