# Generated by Django 5.1.4 on 2025-01-29 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_business_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.business'),
        ),
    ]
