# Generated by Django 5.1.4 on 2025-01-29 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_receipt_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
