# Generated by Django 5.1.4 on 2025-01-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_receipt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
