# Generated by Django 5.1.4 on 2025-01-30 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='signature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.signature'),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
