# Generated by Django 5.1.4 on 2025-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
