# Generated by Django 5.1.4 on 2025-02-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_business_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
