# Generated by Django 5.1.4 on 2025-02-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
