# Generated by Django 5.1.4 on 2025-02-15 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_delete_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('invoice_paid', 'Invoice Paid'), ('invoice_overdue', 'Invoice Overdue'), ('customer_added', 'Customer Added'), ('customer_updated', 'Customer Updated'), ('product_added', 'Product Added'), ('product_updated', 'Product Updated'), ('business_created', 'Business Created'), ('business_updated', 'Business Updated'), ('receipt_created', 'Receipt Created'), ('receipt_updated', 'Receipt Updated'), ('other', 'Other')], max_length=50)),
                ('seen', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noti_business', to='api.business')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
