# Generated by Django 5.1.4 on 2025-02-19 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invoice_created', 'Invoice Created'), ('invoice_updated', 'Invoice Updated'), ('invoice_paid', 'Invoice Paid'), ('invoice_overdue', 'Invoice Overdue'), ('customer_added', 'Customer Added'), ('customer_updated', 'Customer Updated'), ('product_added', 'Product Added'), ('product_updated', 'Product Updated'), ('business_created', 'Business Created'), ('business_updated', 'Business Updated'), ('receipt_created', 'Receipt Created'), ('receipt_updated', 'Receipt Updated'), ('category_created', 'Category Created'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='InvoiceAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.invoice')),
            ],
        ),
    ]
