# Generated by Django 5.1.4 on 2025-02-21 17:41

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_notification_type_invoiceaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='Uid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz1234567890', length=10, max_length=15, prefix='Rcpt-', unique=True),
        ),
    ]
